language: cpp

cache:
    directories:
        - $HOME/.cache

jobs:
    include:
        - os: linux
          script: make && ./configure --disable-doc && make
        - os: osx
          script: make && ./configure --disable-doc && make
        - os: linux
          env: BRANCH=3.15
          install: ./.ci/travis-prepare.sh
          script: ./.ci/travis-epics-build.sh
